I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 34, in script call
    call mechanical_floor_1 from _call_mechanical_floor_1
  File "game/endings.rpy", line 129, in script call
    call MainMenu
  File "game/script.rpy", line 34, in script call
    call mechanical_floor_1 from _call_mechanical_floor_1
  File "game/endings.rpy", line 129, in script call
    call MainMenu
ScriptError: could not find label 'MainMenu'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 34, in script call
    call mechanical_floor_1 from _call_mechanical_floor_1
  File "game/endings.rpy", line 129, in script call
    call MainMenu
  File "C:\Games\renpy-8.3.4-sdk\renpy\ast.py", line 1420, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 34, in script call
    call mechanical_floor_1 from _call_mechanical_floor_1
  File "game/endings.rpy", line 129, in script call
    call MainMenu
  File "C:\Games\renpy-8.3.4-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'MainMenu'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
Cafe of The Dead 1.0
Tue Mar 18 13:21:09 2025
